services:
  db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres:/data

  server:
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  postgres: